// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Salztal.Dienstplanung.Infrastructure.Persistence.ServiceCatalog;

#nullable disable

namespace Salztal.Dienstplanung.Infrastructure.Persistence.ServiceCatalog.Migrations
{
    [DbContext(typeof(ServiceCatalogDbContext))]
    partial class ServiceCatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Salztal.Dienstplanung.Infrastructure.Persistence.ServiceCatalog.ShiftPatternEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AllowedDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayColorCode")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FirstShiftTypeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasInterruption")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SecondShiftTypeId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SwitchRule")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DisplayCode")
                        .IsUnique();

                    b.HasIndex("FirstShiftTypeId");

                    b.HasIndex("Kind")
                        .IsUnique();

                    b.HasIndex("SecondShiftTypeId");

                    b.ToTable("ShiftPatterns", null, t =>
                        {
                            t.HasCheckConstraint("CK_ShiftPatterns_DifferentSegments", "FirstShiftTypeId <> SecondShiftTypeId");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("06fc39e4-1b95-4416-a342-7641d3553fb9"),
                            DisplayCode = "D",
                            FirstShiftTypeId = new Guid("914e5c77-18d6-4813-8212-8765cc0cd647"),
                            HasInterruption = true,
                            Kind = 0,
                            SecondShiftTypeId = new Guid("573e723a-73c9-4b0f-9e91-ecb2462a8df4")
                        },
                        new
                        {
                            Id = new Guid("aa8759ef-2043-4b96-985c-d91d2a20e8a4"),
                            AllowedDay = 6,
                            DisplayCode = "Spr",
                            DisplayColorCode = "blue",
                            FirstShiftTypeId = new Guid("4d6e10ea-a4b9-455c-a868-3a1ab992e856"),
                            HasInterruption = false,
                            Kind = 1,
                            SecondShiftTypeId = new Guid("573e723a-73c9-4b0f-9e91-ecb2462a8df4"),
                            SwitchRule = 0
                        });
                });

            modelBuilder.Entity("Salztal.Dienstplanung.Infrastructure.Persistence.ServiceCatalog.ShiftTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StandardEndMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StandardStartMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkLocationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkLocationId");

                    b.ToTable("ShiftTypes", null, t =>
                        {
                            t.HasCheckConstraint("CK_ShiftTypes_Name_NotEmpty", "length(trim(Name)) > 0");

                            t.HasCheckConstraint("CK_ShiftTypes_StandardTime", "StandardStartMinutes >= 0 AND StandardStartMinutes < 1440 AND StandardEndMinutes > StandardStartMinutes AND StandardEndMinutes < 1440 AND StandardStartMinutes % 30 = 0 AND StandardEndMinutes % 30 = 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("914e5c77-18d6-4813-8212-8765cc0cd647"),
                            Abbreviation = "F",
                            DisplayKind = 0,
                            Name = "Frühdienst",
                            StandardEndMinutes = 810,
                            StandardStartMinutes = 390,
                            WorkLocationId = new Guid("2d2bf3b2-4744-4b56-8515-f33adf9f2161")
                        },
                        new
                        {
                            Id = new Guid("573e723a-73c9-4b0f-9e91-ecb2462a8df4"),
                            Abbreviation = "S",
                            DisplayKind = 0,
                            Name = "Spätdienst",
                            StandardEndMinutes = 1170,
                            StandardStartMinutes = 990,
                            WorkLocationId = new Guid("2d2bf3b2-4744-4b56-8515-f33adf9f2161")
                        },
                        new
                        {
                            Id = new Guid("44fc4ea8-a839-4704-99ef-c8bf2b37f3e0"),
                            DisplayKind = 1,
                            Name = "Cafeteria-Dienst A",
                            StandardEndMinutes = 1230,
                            StandardStartMinutes = 810,
                            WorkLocationId = new Guid("6d38f48b-f938-4aaa-82bd-c59372f599f4")
                        },
                        new
                        {
                            Id = new Guid("4d6e10ea-a4b9-455c-a868-3a1ab992e856"),
                            DisplayKind = 1,
                            Name = "Cafeteria-Dienst B",
                            StandardEndMinutes = 1050,
                            StandardStartMinutes = 810,
                            WorkLocationId = new Guid("6d38f48b-f938-4aaa-82bd-c59372f599f4")
                        });
                });

            modelBuilder.Entity("Salztal.Dienstplanung.Infrastructure.Persistence.ServiceCatalog.WorkLocationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkLocations", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkLocations_ColorCode_NotEmpty", "length(trim(ColorCode)) > 0");

                            t.HasCheckConstraint("CK_WorkLocations_Name_NotEmpty", "length(trim(Name)) > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("6d38f48b-f938-4aaa-82bd-c59372f599f4"),
                            ColorCode = "yellow",
                            Name = "Cafeteria"
                        },
                        new
                        {
                            Id = new Guid("2d2bf3b2-4744-4b56-8515-f33adf9f2161"),
                            ColorCode = "red",
                            Name = "Restaurant"
                        });
                });

            modelBuilder.Entity("Salztal.Dienstplanung.Infrastructure.Persistence.ServiceCatalog.ShiftPatternEntity", b =>
                {
                    b.HasOne("Salztal.Dienstplanung.Infrastructure.Persistence.ServiceCatalog.ShiftTypeEntity", "FirstShiftType")
                        .WithMany()
                        .HasForeignKey("FirstShiftTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Salztal.Dienstplanung.Infrastructure.Persistence.ServiceCatalog.ShiftTypeEntity", "SecondShiftType")
                        .WithMany()
                        .HasForeignKey("SecondShiftTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FirstShiftType");

                    b.Navigation("SecondShiftType");
                });

            modelBuilder.Entity("Salztal.Dienstplanung.Infrastructure.Persistence.ServiceCatalog.ShiftTypeEntity", b =>
                {
                    b.HasOne("Salztal.Dienstplanung.Infrastructure.Persistence.ServiceCatalog.WorkLocationEntity", "WorkLocation")
                        .WithMany()
                        .HasForeignKey("WorkLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkLocation");
                });
#pragma warning restore 612, 618
        }
    }
}
