// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Salztal.Dienstplanung.Infrastructure.Persistence.ServiceCatalog;

#nullable disable

namespace Salztal.Dienstplanung.Infrastructure.Persistence.ServiceCatalog.Migrations
{
    [DbContext(typeof(ServiceCatalogDbContext))]
    partial class ServiceCatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Salztal.Dienstplanung.Infrastructure.Persistence.Availabilities.AvailabilityEntryEntity", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<long>("ChangeVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmployeeId", "Date");

                    b.HasIndex("Date");

                    b.ToTable("AvailabilityEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_AvailabilityEntries_ChangeVersion", "ChangeVersion > 0");

                            t.HasCheckConstraint("CK_AvailabilityEntries_Kind", "Kind IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("Salztal.Dienstplanung.Infrastructure.Persistence.Employees.EmployeeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeTypeId")
                        .IsUnique()
                        .HasFilter("IsActive = 1 AND lower(EmployeeTypeId) = '6197e678-38c8-465c-8d09-fed6812a6f2b'");

                    b.ToTable("Employees", null, t =>
                        {
                            t.HasCheckConstraint("CK_Employees_FirstName_NotEmpty", "length(trim(FirstName)) > 0");

                            t.HasCheckConstraint("CK_Employees_LastName_NotEmpty", "length(trim(LastName)) > 0");
                        });
                });

            modelBuilder.Entity("Salztal.Dienstplanung.Infrastructure.Persistence.Employees.EmployeeTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AbsenceDayValueMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowsAutomaticAssignment")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowsVacationAndSickness")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("ManualSuggestionPriority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanningRole")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PreservesManualAssignmentsOnGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresWeeklyManualAssignment")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeeklyWorkTargetMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("EmployeeTypes", null, t =>
                        {
                            t.HasCheckConstraint("CK_EmployeeTypes_AbsencePolicy", "(AllowsVacationAndSickness = 1 AND AbsenceDayValueMinutes IS NOT NULL AND AbsenceDayValueMinutes > 0 AND AbsenceDayValueMinutes <= 1440) OR (AllowsVacationAndSickness = 0 AND AbsenceDayValueMinutes IS NULL)");

                            t.HasCheckConstraint("CK_EmployeeTypes_Code_NotEmpty", "length(trim(Code)) > 0");

                            t.HasCheckConstraint("CK_EmployeeTypes_ManualSuggestionPriority", "ManualSuggestionPriority IN (0, 1)");

                            t.HasCheckConstraint("CK_EmployeeTypes_Name_NotEmpty", "length(trim(Name)) > 0");

                            t.HasCheckConstraint("CK_EmployeeTypes_PlanningPolicy", "(PlanningRole IN (0, 2) AND AllowsAutomaticAssignment = 1 AND RequiresWeeklyManualAssignment = 0 AND PreservesManualAssignmentsOnGeneration = 0 AND ManualSuggestionPriority = 0) OR (PlanningRole = 1 AND AllowsAutomaticAssignment = 0 AND RequiresWeeklyManualAssignment = 1 AND PreservesManualAssignmentsOnGeneration = 1 AND ManualSuggestionPriority = 1)");

                            t.HasCheckConstraint("CK_EmployeeTypes_PlanningRole", "PlanningRole IN (0, 1, 2)");

                            t.HasCheckConstraint("CK_EmployeeTypes_WeeklyWorkTargetMinutes", "WeeklyWorkTargetMinutes > 0 AND WeeklyWorkTargetMinutes <= 10080");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("6197e678-38c8-465c-8d09-fed6812a6f2b"),
                            AbsenceDayValueMinutes = 480,
                            AllowsAutomaticAssignment = false,
                            AllowsVacationAndSickness = true,
                            Code = "Typ1",
                            ManualSuggestionPriority = 1,
                            Name = "Serviceleitung",
                            PlanningRole = 1,
                            PreservesManualAssignmentsOnGeneration = true,
                            RequiresWeeklyManualAssignment = true,
                            WeeklyWorkTargetMinutes = 2400
                        },
                        new
                        {
                            Id = new Guid("b75fed95-1c2f-439f-9696-217bed8c4d8f"),
                            AbsenceDayValueMinutes = 300,
                            AllowsAutomaticAssignment = true,
                            AllowsVacationAndSickness = true,
                            Code = "Typ25",
                            ManualSuggestionPriority = 0,
                            Name = "Restaurant - 25 Stunden",
                            PlanningRole = 0,
                            PreservesManualAssignmentsOnGeneration = false,
                            RequiresWeeklyManualAssignment = false,
                            WeeklyWorkTargetMinutes = 1500
                        },
                        new
                        {
                            Id = new Guid("6f0feaed-65eb-4568-9c1f-a130cca65e44"),
                            AbsenceDayValueMinutes = 360,
                            AllowsAutomaticAssignment = true,
                            AllowsVacationAndSickness = true,
                            Code = "Typ30",
                            ManualSuggestionPriority = 0,
                            Name = "Restaurant - 30 Stunden",
                            PlanningRole = 0,
                            PreservesManualAssignmentsOnGeneration = false,
                            RequiresWeeklyManualAssignment = false,
                            WeeklyWorkTargetMinutes = 1800
                        },
                        new
                        {
                            Id = new Guid("cc8921a3-83f0-419f-a39b-f8bb37c3d6ba"),
                            AbsenceDayValueMinutes = 360,
                            AllowsAutomaticAssignment = true,
                            AllowsVacationAndSickness = true,
                            Code = "Typ30a",
                            ManualSuggestionPriority = 0,
                            Name = "Alle Dienste - 30 Stunden",
                            PlanningRole = 0,
                            PreservesManualAssignmentsOnGeneration = false,
                            RequiresWeeklyManualAssignment = false,
                            WeeklyWorkTargetMinutes = 1800
                        },
                        new
                        {
                            Id = new Guid("554d2c92-d67e-439c-9bc4-7bbe564198b5"),
                            AbsenceDayValueMinutes = 420,
                            AllowsAutomaticAssignment = true,
                            AllowsVacationAndSickness = true,
                            Code = "Typ35",
                            ManualSuggestionPriority = 0,
                            Name = "Restaurant - 35 Stunden",
                            PlanningRole = 0,
                            PreservesManualAssignmentsOnGeneration = false,
                            RequiresWeeklyManualAssignment = false,
                            WeeklyWorkTargetMinutes = 2100
                        },
                        new
                        {
                            Id = new Guid("e12d71ce-5dca-45b3-bae5-eadebaad93dd"),
                            AbsenceDayValueMinutes = 420,
                            AllowsAutomaticAssignment = true,
                            AllowsVacationAndSickness = true,
                            Code = "Typ35a",
                            ManualSuggestionPriority = 0,
                            Name = "Alle Dienste - 35 Stunden",
                            PlanningRole = 0,
                            PreservesManualAssignmentsOnGeneration = false,
                            RequiresWeeklyManualAssignment = false,
                            WeeklyWorkTargetMinutes = 2100
                        },
                        new
                        {
                            Id = new Guid("86a88720-bcdb-4f56-9dc8-0acf702f00f7"),
                            AllowsAutomaticAssignment = true,
                            AllowsVacationAndSickness = false,
                            Code = "TypAH1",
                            ManualSuggestionPriority = 0,
                            Name = "Restaurant-Spätdienst - 10 Stunden",
                            PlanningRole = 2,
                            PreservesManualAssignmentsOnGeneration = false,
                            RequiresWeeklyManualAssignment = false,
                            WeeklyWorkTargetMinutes = 600
                        },
                        new
                        {
                            Id = new Guid("b4dd7b2a-2b7b-4a8d-b46b-ba1601a5a5a6"),
                            AllowsAutomaticAssignment = true,
                            AllowsVacationAndSickness = false,
                            Code = "TypAH2",
                            ManualSuggestionPriority = 0,
                            Name = "Restaurant, Cafeteria B und Doppeldienst - 10 Stunden",
                            PlanningRole = 2,
                            PreservesManualAssignmentsOnGeneration = false,
                            RequiresWeeklyManualAssignment = false,
                            WeeklyWorkTargetMinutes = 600
                        },
                        new
                        {
                            Id = new Guid("71cc48ce-172a-4580-a6b2-e1acc77b94f6"),
                            AbsenceDayValueMinutes = 240,
                            AllowsAutomaticAssignment = true,
                            AllowsVacationAndSickness = true,
                            Code = "Typ20",
                            ManualSuggestionPriority = 0,
                            Name = "Restaurant - 20 Stunden",
                            PlanningRole = 0,
                            PreservesManualAssignmentsOnGeneration = false,
                            RequiresWeeklyManualAssignment = false,
                            WeeklyWorkTargetMinutes = 1200
                        },
                        new
                        {
                            Id = new Guid("a06b4fcc-dbf1-4b3a-b975-07dc2d488157"),
                            AbsenceDayValueMinutes = 240,
                            AllowsAutomaticAssignment = true,
                            AllowsVacationAndSickness = true,
                            Code = "Typ20a",
                            ManualSuggestionPriority = 0,
                            Name = "Alle Dienste - 20 Stunden",
                            PlanningRole = 0,
                            PreservesManualAssignmentsOnGeneration = false,
                            RequiresWeeklyManualAssignment = false,
                            WeeklyWorkTargetMinutes = 1200
                        },
                        new
                        {
                            Id = new Guid("3c553205-5413-4f0c-ad1c-b4037066470c"),
                            AbsenceDayValueMinutes = 300,
                            AllowsAutomaticAssignment = true,
                            AllowsVacationAndSickness = true,
                            Code = "Typ25a",
                            ManualSuggestionPriority = 0,
                            Name = "Alle Dienste - 25 Stunden",
                            PlanningRole = 0,
                            PreservesManualAssignmentsOnGeneration = false,
                            RequiresWeeklyManualAssignment = false,
                            WeeklyWorkTargetMinutes = 1500
                        });
                });

            modelBuilder.Entity("Salztal.Dienstplanung.Infrastructure.Persistence.Employees.EmployeeTypeShiftEligibilityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Activation")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EmployeeTypeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ShiftPatternId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ShiftTypeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetKind")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShiftPatternId");

                    b.HasIndex("ShiftTypeId");

                    b.HasIndex("EmployeeTypeId", "ShiftTypeId", "Mode")
                        .IsUnique()
                        .HasFilter("TargetKind = 0");

                    b.HasIndex("EmployeeTypeId", "ShiftPatternId", "Mode", "Activation")
                        .IsUnique()
                        .HasFilter("TargetKind = 1");

                    b.ToTable("EmployeeTypeShiftEligibilities", null, t =>
                        {
                            t.HasCheckConstraint("CK_EmployeeTypeShiftEligibilities_Activation", "Activation IN (0, 1)");

                            t.HasCheckConstraint("CK_EmployeeTypeShiftEligibilities_Mode", "Mode IN (0, 1)");

                            t.HasCheckConstraint("CK_EmployeeTypeShiftEligibilities_ShiftTypeActivation", "TargetKind <> 0 OR Activation = 0");

                            t.HasCheckConstraint("CK_EmployeeTypeShiftEligibilities_Target", "(TargetKind = 0 AND ShiftTypeId IS NOT NULL AND ShiftPatternId IS NULL) OR (TargetKind = 1 AND ShiftTypeId IS NULL AND ShiftPatternId IS NOT NULL)");

                            t.HasCheckConstraint("CK_EmployeeTypeShiftEligibilities_TargetKind", "TargetKind IN (0, 1)");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activation = 0,
                            EmployeeTypeId = new Guid("6197e678-38c8-465c-8d09-fed6812a6f2b"),
                            Mode = 0,
                            ShiftTypeId = new Guid("914e5c77-18d6-4813-8212-8765cc0cd647"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 2,
                            Activation = 0,
                            EmployeeTypeId = new Guid("6197e678-38c8-465c-8d09-fed6812a6f2b"),
                            Mode = 0,
                            ShiftTypeId = new Guid("573e723a-73c9-4b0f-9e91-ecb2462a8df4"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 3,
                            Activation = 0,
                            EmployeeTypeId = new Guid("6197e678-38c8-465c-8d09-fed6812a6f2b"),
                            Mode = 0,
                            ShiftTypeId = new Guid("44fc4ea8-a839-4704-99ef-c8bf2b37f3e0"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 4,
                            Activation = 0,
                            EmployeeTypeId = new Guid("6197e678-38c8-465c-8d09-fed6812a6f2b"),
                            Mode = 0,
                            ShiftTypeId = new Guid("4d6e10ea-a4b9-455c-a868-3a1ab992e856"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 5,
                            Activation = 0,
                            EmployeeTypeId = new Guid("6197e678-38c8-465c-8d09-fed6812a6f2b"),
                            Mode = 0,
                            ShiftPatternId = new Guid("06fc39e4-1b95-4416-a342-7641d3553fb9"),
                            TargetKind = 1
                        },
                        new
                        {
                            Id = 6,
                            Activation = 0,
                            EmployeeTypeId = new Guid("6197e678-38c8-465c-8d09-fed6812a6f2b"),
                            Mode = 0,
                            ShiftPatternId = new Guid("aa8759ef-2043-4b96-985c-d91d2a20e8a4"),
                            TargetKind = 1
                        },
                        new
                        {
                            Id = 7,
                            Activation = 0,
                            EmployeeTypeId = new Guid("6197e678-38c8-465c-8d09-fed6812a6f2b"),
                            Mode = 1,
                            ShiftTypeId = new Guid("914e5c77-18d6-4813-8212-8765cc0cd647"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 8,
                            Activation = 0,
                            EmployeeTypeId = new Guid("6197e678-38c8-465c-8d09-fed6812a6f2b"),
                            Mode = 1,
                            ShiftTypeId = new Guid("573e723a-73c9-4b0f-9e91-ecb2462a8df4"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 9,
                            Activation = 0,
                            EmployeeTypeId = new Guid("6197e678-38c8-465c-8d09-fed6812a6f2b"),
                            Mode = 1,
                            ShiftTypeId = new Guid("44fc4ea8-a839-4704-99ef-c8bf2b37f3e0"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 10,
                            Activation = 0,
                            EmployeeTypeId = new Guid("6197e678-38c8-465c-8d09-fed6812a6f2b"),
                            Mode = 1,
                            ShiftTypeId = new Guid("4d6e10ea-a4b9-455c-a868-3a1ab992e856"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 11,
                            Activation = 0,
                            EmployeeTypeId = new Guid("b75fed95-1c2f-439f-9696-217bed8c4d8f"),
                            Mode = 0,
                            ShiftTypeId = new Guid("914e5c77-18d6-4813-8212-8765cc0cd647"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 12,
                            Activation = 0,
                            EmployeeTypeId = new Guid("b75fed95-1c2f-439f-9696-217bed8c4d8f"),
                            Mode = 0,
                            ShiftTypeId = new Guid("573e723a-73c9-4b0f-9e91-ecb2462a8df4"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 13,
                            Activation = 0,
                            EmployeeTypeId = new Guid("b75fed95-1c2f-439f-9696-217bed8c4d8f"),
                            Mode = 0,
                            ShiftPatternId = new Guid("06fc39e4-1b95-4416-a342-7641d3553fb9"),
                            TargetKind = 1
                        },
                        new
                        {
                            Id = 14,
                            Activation = 0,
                            EmployeeTypeId = new Guid("6f0feaed-65eb-4568-9c1f-a130cca65e44"),
                            Mode = 0,
                            ShiftTypeId = new Guid("914e5c77-18d6-4813-8212-8765cc0cd647"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 15,
                            Activation = 0,
                            EmployeeTypeId = new Guid("6f0feaed-65eb-4568-9c1f-a130cca65e44"),
                            Mode = 0,
                            ShiftTypeId = new Guid("573e723a-73c9-4b0f-9e91-ecb2462a8df4"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 16,
                            Activation = 0,
                            EmployeeTypeId = new Guid("6f0feaed-65eb-4568-9c1f-a130cca65e44"),
                            Mode = 0,
                            ShiftPatternId = new Guid("06fc39e4-1b95-4416-a342-7641d3553fb9"),
                            TargetKind = 1
                        },
                        new
                        {
                            Id = 17,
                            Activation = 0,
                            EmployeeTypeId = new Guid("cc8921a3-83f0-419f-a39b-f8bb37c3d6ba"),
                            Mode = 0,
                            ShiftTypeId = new Guid("914e5c77-18d6-4813-8212-8765cc0cd647"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 18,
                            Activation = 0,
                            EmployeeTypeId = new Guid("cc8921a3-83f0-419f-a39b-f8bb37c3d6ba"),
                            Mode = 0,
                            ShiftTypeId = new Guid("573e723a-73c9-4b0f-9e91-ecb2462a8df4"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 19,
                            Activation = 0,
                            EmployeeTypeId = new Guid("cc8921a3-83f0-419f-a39b-f8bb37c3d6ba"),
                            Mode = 0,
                            ShiftTypeId = new Guid("44fc4ea8-a839-4704-99ef-c8bf2b37f3e0"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 20,
                            Activation = 0,
                            EmployeeTypeId = new Guid("cc8921a3-83f0-419f-a39b-f8bb37c3d6ba"),
                            Mode = 0,
                            ShiftTypeId = new Guid("4d6e10ea-a4b9-455c-a868-3a1ab992e856"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 21,
                            Activation = 0,
                            EmployeeTypeId = new Guid("cc8921a3-83f0-419f-a39b-f8bb37c3d6ba"),
                            Mode = 0,
                            ShiftPatternId = new Guid("06fc39e4-1b95-4416-a342-7641d3553fb9"),
                            TargetKind = 1
                        },
                        new
                        {
                            Id = 22,
                            Activation = 0,
                            EmployeeTypeId = new Guid("cc8921a3-83f0-419f-a39b-f8bb37c3d6ba"),
                            Mode = 0,
                            ShiftPatternId = new Guid("aa8759ef-2043-4b96-985c-d91d2a20e8a4"),
                            TargetKind = 1
                        },
                        new
                        {
                            Id = 23,
                            Activation = 0,
                            EmployeeTypeId = new Guid("554d2c92-d67e-439c-9bc4-7bbe564198b5"),
                            Mode = 0,
                            ShiftTypeId = new Guid("914e5c77-18d6-4813-8212-8765cc0cd647"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 24,
                            Activation = 0,
                            EmployeeTypeId = new Guid("554d2c92-d67e-439c-9bc4-7bbe564198b5"),
                            Mode = 0,
                            ShiftTypeId = new Guid("573e723a-73c9-4b0f-9e91-ecb2462a8df4"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 25,
                            Activation = 0,
                            EmployeeTypeId = new Guid("554d2c92-d67e-439c-9bc4-7bbe564198b5"),
                            Mode = 0,
                            ShiftPatternId = new Guid("06fc39e4-1b95-4416-a342-7641d3553fb9"),
                            TargetKind = 1
                        },
                        new
                        {
                            Id = 26,
                            Activation = 0,
                            EmployeeTypeId = new Guid("e12d71ce-5dca-45b3-bae5-eadebaad93dd"),
                            Mode = 0,
                            ShiftTypeId = new Guid("914e5c77-18d6-4813-8212-8765cc0cd647"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 27,
                            Activation = 0,
                            EmployeeTypeId = new Guid("e12d71ce-5dca-45b3-bae5-eadebaad93dd"),
                            Mode = 0,
                            ShiftTypeId = new Guid("573e723a-73c9-4b0f-9e91-ecb2462a8df4"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 28,
                            Activation = 0,
                            EmployeeTypeId = new Guid("e12d71ce-5dca-45b3-bae5-eadebaad93dd"),
                            Mode = 0,
                            ShiftTypeId = new Guid("44fc4ea8-a839-4704-99ef-c8bf2b37f3e0"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 29,
                            Activation = 0,
                            EmployeeTypeId = new Guid("e12d71ce-5dca-45b3-bae5-eadebaad93dd"),
                            Mode = 0,
                            ShiftTypeId = new Guid("4d6e10ea-a4b9-455c-a868-3a1ab992e856"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 30,
                            Activation = 0,
                            EmployeeTypeId = new Guid("e12d71ce-5dca-45b3-bae5-eadebaad93dd"),
                            Mode = 0,
                            ShiftPatternId = new Guid("06fc39e4-1b95-4416-a342-7641d3553fb9"),
                            TargetKind = 1
                        },
                        new
                        {
                            Id = 31,
                            Activation = 0,
                            EmployeeTypeId = new Guid("e12d71ce-5dca-45b3-bae5-eadebaad93dd"),
                            Mode = 0,
                            ShiftPatternId = new Guid("aa8759ef-2043-4b96-985c-d91d2a20e8a4"),
                            TargetKind = 1
                        },
                        new
                        {
                            Id = 32,
                            Activation = 0,
                            EmployeeTypeId = new Guid("86a88720-bcdb-4f56-9dc8-0acf702f00f7"),
                            Mode = 0,
                            ShiftTypeId = new Guid("573e723a-73c9-4b0f-9e91-ecb2462a8df4"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 33,
                            Activation = 0,
                            EmployeeTypeId = new Guid("86a88720-bcdb-4f56-9dc8-0acf702f00f7"),
                            Mode = 1,
                            ShiftTypeId = new Guid("914e5c77-18d6-4813-8212-8765cc0cd647"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 34,
                            Activation = 0,
                            EmployeeTypeId = new Guid("b4dd7b2a-2b7b-4a8d-b46b-ba1601a5a5a6"),
                            Mode = 0,
                            ShiftTypeId = new Guid("573e723a-73c9-4b0f-9e91-ecb2462a8df4"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 35,
                            Activation = 0,
                            EmployeeTypeId = new Guid("b4dd7b2a-2b7b-4a8d-b46b-ba1601a5a5a6"),
                            Mode = 0,
                            ShiftTypeId = new Guid("4d6e10ea-a4b9-455c-a868-3a1ab992e856"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 36,
                            Activation = 0,
                            EmployeeTypeId = new Guid("b4dd7b2a-2b7b-4a8d-b46b-ba1601a5a5a6"),
                            Mode = 0,
                            ShiftPatternId = new Guid("06fc39e4-1b95-4416-a342-7641d3553fb9"),
                            TargetKind = 1
                        },
                        new
                        {
                            Id = 37,
                            Activation = 0,
                            EmployeeTypeId = new Guid("b4dd7b2a-2b7b-4a8d-b46b-ba1601a5a5a6"),
                            Mode = 1,
                            ShiftTypeId = new Guid("914e5c77-18d6-4813-8212-8765cc0cd647"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 38,
                            Activation = 1,
                            EmployeeTypeId = new Guid("b4dd7b2a-2b7b-4a8d-b46b-ba1601a5a5a6"),
                            Mode = 0,
                            ShiftPatternId = new Guid("aa8759ef-2043-4b96-985c-d91d2a20e8a4"),
                            TargetKind = 1
                        },
                        new
                        {
                            Id = 39,
                            Activation = 0,
                            EmployeeTypeId = new Guid("71cc48ce-172a-4580-a6b2-e1acc77b94f6"),
                            Mode = 0,
                            ShiftTypeId = new Guid("914e5c77-18d6-4813-8212-8765cc0cd647"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 40,
                            Activation = 0,
                            EmployeeTypeId = new Guid("71cc48ce-172a-4580-a6b2-e1acc77b94f6"),
                            Mode = 0,
                            ShiftTypeId = new Guid("573e723a-73c9-4b0f-9e91-ecb2462a8df4"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 41,
                            Activation = 0,
                            EmployeeTypeId = new Guid("71cc48ce-172a-4580-a6b2-e1acc77b94f6"),
                            Mode = 0,
                            ShiftPatternId = new Guid("06fc39e4-1b95-4416-a342-7641d3553fb9"),
                            TargetKind = 1
                        },
                        new
                        {
                            Id = 42,
                            Activation = 0,
                            EmployeeTypeId = new Guid("a06b4fcc-dbf1-4b3a-b975-07dc2d488157"),
                            Mode = 0,
                            ShiftTypeId = new Guid("914e5c77-18d6-4813-8212-8765cc0cd647"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 43,
                            Activation = 0,
                            EmployeeTypeId = new Guid("a06b4fcc-dbf1-4b3a-b975-07dc2d488157"),
                            Mode = 0,
                            ShiftTypeId = new Guid("573e723a-73c9-4b0f-9e91-ecb2462a8df4"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 44,
                            Activation = 0,
                            EmployeeTypeId = new Guid("a06b4fcc-dbf1-4b3a-b975-07dc2d488157"),
                            Mode = 0,
                            ShiftTypeId = new Guid("44fc4ea8-a839-4704-99ef-c8bf2b37f3e0"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 45,
                            Activation = 0,
                            EmployeeTypeId = new Guid("a06b4fcc-dbf1-4b3a-b975-07dc2d488157"),
                            Mode = 0,
                            ShiftTypeId = new Guid("4d6e10ea-a4b9-455c-a868-3a1ab992e856"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 46,
                            Activation = 0,
                            EmployeeTypeId = new Guid("a06b4fcc-dbf1-4b3a-b975-07dc2d488157"),
                            Mode = 0,
                            ShiftPatternId = new Guid("06fc39e4-1b95-4416-a342-7641d3553fb9"),
                            TargetKind = 1
                        },
                        new
                        {
                            Id = 47,
                            Activation = 0,
                            EmployeeTypeId = new Guid("a06b4fcc-dbf1-4b3a-b975-07dc2d488157"),
                            Mode = 0,
                            ShiftPatternId = new Guid("aa8759ef-2043-4b96-985c-d91d2a20e8a4"),
                            TargetKind = 1
                        },
                        new
                        {
                            Id = 48,
                            Activation = 0,
                            EmployeeTypeId = new Guid("3c553205-5413-4f0c-ad1c-b4037066470c"),
                            Mode = 0,
                            ShiftTypeId = new Guid("914e5c77-18d6-4813-8212-8765cc0cd647"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 49,
                            Activation = 0,
                            EmployeeTypeId = new Guid("3c553205-5413-4f0c-ad1c-b4037066470c"),
                            Mode = 0,
                            ShiftTypeId = new Guid("573e723a-73c9-4b0f-9e91-ecb2462a8df4"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 50,
                            Activation = 0,
                            EmployeeTypeId = new Guid("3c553205-5413-4f0c-ad1c-b4037066470c"),
                            Mode = 0,
                            ShiftTypeId = new Guid("44fc4ea8-a839-4704-99ef-c8bf2b37f3e0"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 51,
                            Activation = 0,
                            EmployeeTypeId = new Guid("3c553205-5413-4f0c-ad1c-b4037066470c"),
                            Mode = 0,
                            ShiftTypeId = new Guid("4d6e10ea-a4b9-455c-a868-3a1ab992e856"),
                            TargetKind = 0
                        },
                        new
                        {
                            Id = 52,
                            Activation = 0,
                            EmployeeTypeId = new Guid("3c553205-5413-4f0c-ad1c-b4037066470c"),
                            Mode = 0,
                            ShiftPatternId = new Guid("06fc39e4-1b95-4416-a342-7641d3553fb9"),
                            TargetKind = 1
                        },
                        new
                        {
                            Id = 53,
                            Activation = 0,
                            EmployeeTypeId = new Guid("3c553205-5413-4f0c-ad1c-b4037066470c"),
                            Mode = 0,
                            ShiftPatternId = new Guid("aa8759ef-2043-4b96-985c-d91d2a20e8a4"),
                            TargetKind = 1
                        });
                });

            modelBuilder.Entity("Salztal.Dienstplanung.Infrastructure.Persistence.ServiceCatalog.ShiftPatternEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AllowedDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayColorCode")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FirstShiftTypeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasInterruption")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SecondShiftTypeId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SwitchRule")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DisplayCode")
                        .IsUnique();

                    b.HasIndex("FirstShiftTypeId");

                    b.HasIndex("Kind")
                        .IsUnique();

                    b.HasIndex("SecondShiftTypeId");

                    b.ToTable("ShiftPatterns", null, t =>
                        {
                            t.HasCheckConstraint("CK_ShiftPatterns_DifferentSegments", "FirstShiftTypeId <> SecondShiftTypeId");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("06fc39e4-1b95-4416-a342-7641d3553fb9"),
                            DisplayCode = "D",
                            FirstShiftTypeId = new Guid("914e5c77-18d6-4813-8212-8765cc0cd647"),
                            HasInterruption = true,
                            Kind = 0,
                            SecondShiftTypeId = new Guid("573e723a-73c9-4b0f-9e91-ecb2462a8df4")
                        },
                        new
                        {
                            Id = new Guid("aa8759ef-2043-4b96-985c-d91d2a20e8a4"),
                            AllowedDay = 6,
                            DisplayCode = "Spr",
                            DisplayColorCode = "blue",
                            FirstShiftTypeId = new Guid("4d6e10ea-a4b9-455c-a868-3a1ab992e856"),
                            HasInterruption = false,
                            Kind = 1,
                            SecondShiftTypeId = new Guid("573e723a-73c9-4b0f-9e91-ecb2462a8df4"),
                            SwitchRule = 0
                        });
                });

            modelBuilder.Entity("Salztal.Dienstplanung.Infrastructure.Persistence.ServiceCatalog.ShiftTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StandardEndMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StandardStartMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkLocationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkLocationId");

                    b.ToTable("ShiftTypes", null, t =>
                        {
                            t.HasCheckConstraint("CK_ShiftTypes_Name_NotEmpty", "length(trim(Name)) > 0");

                            t.HasCheckConstraint("CK_ShiftTypes_StandardTime", "StandardStartMinutes >= 0 AND StandardStartMinutes < 1440 AND StandardEndMinutes > StandardStartMinutes AND StandardEndMinutes < 1440 AND StandardStartMinutes % 30 = 0 AND StandardEndMinutes % 30 = 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("914e5c77-18d6-4813-8212-8765cc0cd647"),
                            Abbreviation = "F",
                            DisplayKind = 0,
                            Name = "Frühdienst",
                            StandardEndMinutes = 810,
                            StandardStartMinutes = 390,
                            WorkLocationId = new Guid("2d2bf3b2-4744-4b56-8515-f33adf9f2161")
                        },
                        new
                        {
                            Id = new Guid("573e723a-73c9-4b0f-9e91-ecb2462a8df4"),
                            Abbreviation = "S",
                            DisplayKind = 0,
                            Name = "Spätdienst",
                            StandardEndMinutes = 1170,
                            StandardStartMinutes = 990,
                            WorkLocationId = new Guid("2d2bf3b2-4744-4b56-8515-f33adf9f2161")
                        },
                        new
                        {
                            Id = new Guid("44fc4ea8-a839-4704-99ef-c8bf2b37f3e0"),
                            DisplayKind = 1,
                            Name = "Cafeteria-Dienst A",
                            StandardEndMinutes = 1230,
                            StandardStartMinutes = 810,
                            WorkLocationId = new Guid("6d38f48b-f938-4aaa-82bd-c59372f599f4")
                        },
                        new
                        {
                            Id = new Guid("4d6e10ea-a4b9-455c-a868-3a1ab992e856"),
                            DisplayKind = 1,
                            Name = "Cafeteria-Dienst B",
                            StandardEndMinutes = 1050,
                            StandardStartMinutes = 810,
                            WorkLocationId = new Guid("6d38f48b-f938-4aaa-82bd-c59372f599f4")
                        });
                });

            modelBuilder.Entity("Salztal.Dienstplanung.Infrastructure.Persistence.ServiceCatalog.WorkLocationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkLocations", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkLocations_ColorCode_NotEmpty", "length(trim(ColorCode)) > 0");

                            t.HasCheckConstraint("CK_WorkLocations_Name_NotEmpty", "length(trim(Name)) > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("6d38f48b-f938-4aaa-82bd-c59372f599f4"),
                            ColorCode = "yellow",
                            Name = "Cafeteria"
                        },
                        new
                        {
                            Id = new Guid("2d2bf3b2-4744-4b56-8515-f33adf9f2161"),
                            ColorCode = "red",
                            Name = "Restaurant"
                        });
                });

            modelBuilder.Entity("Salztal.Dienstplanung.Infrastructure.Persistence.StaffingDemands.StaffingDemandDateExceptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ActualEndMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActualStartMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RequiredEmployeeCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ShiftTypeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkLocationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShiftTypeId");

                    b.HasIndex("WorkLocationId");

                    b.HasIndex("Date", "WorkLocationId", "ShiftTypeId")
                        .IsUnique();

                    b.ToTable("StaffingDemandDateExceptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_StaffingDemandDateExceptions_Kind", "Kind IN (0, 1, 2)");

                            t.HasCheckConstraint("CK_StaffingDemandDateExceptions_ValueShape", "(Kind = 2 AND ActualStartMinutes IS NULL AND ActualEndMinutes IS NULL AND RequiredEmployeeCount IS NULL) OR (Kind IN (0, 1) AND ActualStartMinutes IS NOT NULL AND ActualEndMinutes IS NOT NULL AND RequiredEmployeeCount IS NOT NULL AND ActualStartMinutes >= 0 AND ActualStartMinutes < 1440 AND ActualEndMinutes > ActualStartMinutes AND ActualEndMinutes < 1440 AND ActualStartMinutes % 30 = 0 AND ActualEndMinutes % 30 = 0 AND RequiredEmployeeCount > 0)");
                        });
                });

            modelBuilder.Entity("Salztal.Dienstplanung.Infrastructure.Persistence.StaffingDemands.StandardStaffingDemandRevisionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ActualEndMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActualStartMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CorrectionSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EffectiveFromMonday")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RequiredEmployeeCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ShiftTypeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkLocationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShiftTypeId");

                    b.HasIndex("WorkLocationId");

                    b.HasIndex("DayOfWeek", "WorkLocationId", "ShiftTypeId", "EffectiveFromMonday", "CorrectionSequence")
                        .IsUnique();

                    b.ToTable("StandardStaffingDemandRevisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_StandardStaffingDemandRevisions_CorrectionSequence", "CorrectionSequence > 0");

                            t.HasCheckConstraint("CK_StandardStaffingDemandRevisions_DayOfWeek", "DayOfWeek >= 0 AND DayOfWeek <= 6");

                            t.HasCheckConstraint("CK_StandardStaffingDemandRevisions_EffectiveMonday", "strftime('%w', EffectiveFromMonday) = '1'");

                            t.HasCheckConstraint("CK_StandardStaffingDemandRevisions_Kind", "Kind IN (0, 1, 2)");

                            t.HasCheckConstraint("CK_StandardStaffingDemandRevisions_ValueShape", "(Kind = 2 AND ActualStartMinutes IS NULL AND ActualEndMinutes IS NULL AND RequiredEmployeeCount IS NULL) OR (Kind IN (0, 1) AND ActualStartMinutes IS NOT NULL AND ActualEndMinutes IS NOT NULL AND RequiredEmployeeCount IS NOT NULL AND ActualStartMinutes >= 0 AND ActualStartMinutes < 1440 AND ActualEndMinutes > ActualStartMinutes AND ActualEndMinutes < 1440 AND ActualStartMinutes % 30 = 0 AND ActualEndMinutes % 30 = 0 AND RequiredEmployeeCount > 0)");
                        });
                });

            modelBuilder.Entity("Salztal.Dienstplanung.Infrastructure.Persistence.Availabilities.AvailabilityEntryEntity", b =>
                {
                    b.HasOne("Salztal.Dienstplanung.Infrastructure.Persistence.Employees.EmployeeEntity", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Salztal.Dienstplanung.Infrastructure.Persistence.Employees.EmployeeEntity", b =>
                {
                    b.HasOne("Salztal.Dienstplanung.Infrastructure.Persistence.Employees.EmployeeTypeEntity", "EmployeeType")
                        .WithMany()
                        .HasForeignKey("EmployeeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmployeeType");
                });

            modelBuilder.Entity("Salztal.Dienstplanung.Infrastructure.Persistence.Employees.EmployeeTypeShiftEligibilityEntity", b =>
                {
                    b.HasOne("Salztal.Dienstplanung.Infrastructure.Persistence.Employees.EmployeeTypeEntity", "EmployeeType")
                        .WithMany("ShiftEligibilities")
                        .HasForeignKey("EmployeeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Salztal.Dienstplanung.Infrastructure.Persistence.ServiceCatalog.ShiftPatternEntity", "ShiftPattern")
                        .WithMany()
                        .HasForeignKey("ShiftPatternId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Salztal.Dienstplanung.Infrastructure.Persistence.ServiceCatalog.ShiftTypeEntity", "ShiftType")
                        .WithMany()
                        .HasForeignKey("ShiftTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EmployeeType");

                    b.Navigation("ShiftPattern");

                    b.Navigation("ShiftType");
                });

            modelBuilder.Entity("Salztal.Dienstplanung.Infrastructure.Persistence.ServiceCatalog.ShiftPatternEntity", b =>
                {
                    b.HasOne("Salztal.Dienstplanung.Infrastructure.Persistence.ServiceCatalog.ShiftTypeEntity", "FirstShiftType")
                        .WithMany()
                        .HasForeignKey("FirstShiftTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Salztal.Dienstplanung.Infrastructure.Persistence.ServiceCatalog.ShiftTypeEntity", "SecondShiftType")
                        .WithMany()
                        .HasForeignKey("SecondShiftTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FirstShiftType");

                    b.Navigation("SecondShiftType");
                });

            modelBuilder.Entity("Salztal.Dienstplanung.Infrastructure.Persistence.ServiceCatalog.ShiftTypeEntity", b =>
                {
                    b.HasOne("Salztal.Dienstplanung.Infrastructure.Persistence.ServiceCatalog.WorkLocationEntity", "WorkLocation")
                        .WithMany()
                        .HasForeignKey("WorkLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkLocation");
                });

            modelBuilder.Entity("Salztal.Dienstplanung.Infrastructure.Persistence.StaffingDemands.StaffingDemandDateExceptionEntity", b =>
                {
                    b.HasOne("Salztal.Dienstplanung.Infrastructure.Persistence.ServiceCatalog.ShiftTypeEntity", "ShiftType")
                        .WithMany()
                        .HasForeignKey("ShiftTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Salztal.Dienstplanung.Infrastructure.Persistence.ServiceCatalog.WorkLocationEntity", "WorkLocation")
                        .WithMany()
                        .HasForeignKey("WorkLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ShiftType");

                    b.Navigation("WorkLocation");
                });

            modelBuilder.Entity("Salztal.Dienstplanung.Infrastructure.Persistence.StaffingDemands.StandardStaffingDemandRevisionEntity", b =>
                {
                    b.HasOne("Salztal.Dienstplanung.Infrastructure.Persistence.ServiceCatalog.ShiftTypeEntity", "ShiftType")
                        .WithMany()
                        .HasForeignKey("ShiftTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Salztal.Dienstplanung.Infrastructure.Persistence.ServiceCatalog.WorkLocationEntity", "WorkLocation")
                        .WithMany()
                        .HasForeignKey("WorkLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ShiftType");

                    b.Navigation("WorkLocation");
                });

            modelBuilder.Entity("Salztal.Dienstplanung.Infrastructure.Persistence.Employees.EmployeeTypeEntity", b =>
                {
                    b.Navigation("ShiftEligibilities");
                });
#pragma warning restore 612, 618
        }
    }
}
