<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Google.OrTools" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Salztal.Dienstplanung.Application\Salztal.Dienstplanung.Application.csproj" />
    <ProjectReference Include="..\Salztal.Dienstplanung.Domain\Salztal.Dienstplanung.Domain.csproj" />
  </ItemGroup>
</Project>
